### ISSUE TITLE
Use yoda conditions for conditional statements

### ISSUE THREAD

**Issue by mgratch** [ViewFromTheBox/GravityView#2]
Read about them here:
https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#yoda-conditions

I would also recommend shortening the code with ternary operators.  You will noticed they are used throughout GV codebase.
https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#ternary-operator

https://github.com/ViewFromTheBox/GravityView/blob/13ac3ca7310e0d074ccaac4e907b6a0ddbdb1ce7/includes/fields/class-gravityview-field-fileupload.php#L113-L119

`$file_path = false !== strpos($file_path, 'www.dropbox') ? str_replace("www.dropbox","dl.dropboxusercontent",$file_path) : $file_path;`

**Comment by ViewFromTheBox** [comment]
https://github.com/ViewFromTheBox/GravityView/blob/issue/1/includes/fields/class-gravityview-field-fileupload.php

Switch the conditionals to Yoda conditionals.
