### ISSUE TITLE
Make sure we are respecting the "Link to file" option

### ISSUE THREAD

**Issue by mgratch** [ViewFromTheBox/GravityView#3]
https://github.com/ViewFromTheBox/GravityView/blob/13ac3ca7310e0d074ccaac4e907b6a0ddbdb1ce7/includes/fields/class-gravityview-field-fileupload.php#L231-L239

**Comment by ViewFromTheBox** [comment]
https://github.com/ViewFromTheBox/GravityView/blob/issue/1/includes/fields/class-gravityview-field-fileupload.php

Made sure our addition respects the link to file option.
