### ISSUE TITLE
Create a filter to choose default behavior 

### ISSUE THREAD

**Issue by mgratch** [ViewFromTheBox/GravityView#4]
https://github.com/ViewFromTheBox/GravityView/blob/13ac3ca7310e0d074ccaac4e907b6a0ddbdb1ce7/includes/fields/class-gravityview-field-fileupload.php#L113-L119

https://developer.wordpress.org/reference/functions/apply_filters/

By default I would have the filter prevent changing the dropbox URL unless a developer chooses to `add_filter` themselves, this will prevent any sudden changes for users already using the extension.  In a future update perhaps we can check if the DB extension is active and provide a [UI option](
https://github.com/ViewFromTheBox/GravityView/blob/13ac3ca7310e0d074ccaac4e907b6a0ddbdb1ce7/includes/fields/class-gravityview-field-fileupload.php#L25-L42) to allow the customer to determine layout type.

**Comment by ViewFromTheBox** [comment]
https://github.com/ViewFromTheBox/GravityView/blob/issue/1/includes/fields/class-gravityview-field-fileupload.php

Added the filter for default behavior for the dropbox link.
